/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.testng;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class GroupsTest {
    @BeforeGroups("entry")
    public void ResetDBEntries() {
        System.out.println("Database reset");
    }

    @AfterGroups("entry")
    public void DeleteUser() {
        System.out.println("User is deleted");
    }

    @Test(groups = "general")
    public void TestAppHasAGreeting() {
        App classUnderTest = new App();
        System.out.println("General TC");
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test(groups = "entry", dependsOnMethods = {"TestAppRegistration"})
    public void TestAppLogin() {
        App classUnderTest = new App();
        System.out.println("Login");
        classUnderTest.AppLogin();
    }

    @Test(groups = {"entry", "general"})
    public void TestAppRegistration() {
        App classUnderTest = new App();
        System.out.println("Registration");
        classUnderTest.AppRegistration();
    }

}
