/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.testng;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String AppLogin() {
        return "User in logged in";
    }

    public String AppRegistration() {
        return "User is registered";
    }

    public static void data(String firstname, String lastname) {
        System.out.println("My name is " + lastname + " " + firstname);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
